import sys
from pathlib import Path

# Append project root to PYTHONPATH
project_root = Path(__file__).resolve().parent.parent
sys.path.append(str(project_root))

from src.vlm_backend import load_model, generate_action

def test_smolvlm_inference():
    """
    Validates model loading and executes a short visual prompt on a local screenshot using SmolVLM.
    """
    print("\n=== Local SmolVLM Inference Test ===")
    
    # 1. Verify model and processor loading
    try:
        model, processor, device = load_model()
        print(f"Model loaded successfully. Active device: {device}")
    except Exception as e:
        print(f"Error loading model from config path: {e}")
        print("Ensure SmolVLM-256M-Instruct is downloaded locally under models/ directory.")
        raise e

    # 2. Setup a dummy HMI screenshot if not present
    image_path = Path("screenshots/current.png")
    if not image_path.exists():
        from PIL import Image
        image_path.parent.mkdir(exist_ok=True)
        img = Image.new("RGB", (1600, 900), color="#0b0e14")
        img.save(image_path)
        print(f"Created a dummy screenshot at '{image_path}' for testing.")

    # 3. Test generate_action
    try:
        system_prompt = "Output only a JSON containing: {\"status\": \"success\"}."
        prompt = "Perform a diagnostic connection check."
        response = generate_action(system_prompt, prompt, image_path=str(image_path))
        print(f"Raw Model Response: '{response}'")
        assert len(response) > 0, "The response generated by SmolVLM was empty."
        print("Success: Local SmolVLM model inference completed and verified.")
    except Exception as e:
        print(f"Error executing local SmolVLM inference: {e}")
        raise e
        
    print("========================================\n")

if __name__ == "__main__":
    test_smolvlm_inference()
